config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  resources :users do
    resources :favorites, only: [:index]
  end
  resources :reviews, only: [:index]
  resources :ranks, only: [:index]
  resources :games do
    resources :reviews
    collection do
      get :rank
      get :search
    end
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :game
  
end

app/models/game.rb
class Game < ApplicationRecord
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :title, presence: true, uniqueness: true
  validates :genre, presence: { message: "を選択してください"}
  validates :participation, presence: { message: "を選択してください"}
  validates :target_age, presence: { message: "を選択してください"}
  validates :play_time, presence: { message: "を選択してください"}
  validates :price, presence: { message: "を選択してください"}
  validate :image_size
  
  belongs_to :user
  has_many :reviews
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"  

  mount_uploader :image, ImageUploader
  
  def self.search(search)
    if search
      where(["title LIKE ?", "%#{search}%"])
    else
      all
    end
  end
  
  private
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "5MB以内の画像にしてください")
      end
    end
  
end

app/models/review.rb
class Review < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  validates :evalution, presence: { message: "を選択してください" }
  validates :comment, presence: true, length: { maximum: 500 }
  
  belongs_to :user
  belongs_to :game
  
end

app/models/user.rb
class User < ApplicationRecord
  
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
  VALID_PASSWORED_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :description, length: { maximum: 150 }
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :password_digest, length: { minimum: 6 },  allow_nil: true
  
  has_secure_password
  mount_uploader :image, ImageUploader
  
  has_many :topics
  has_many :reviews
  has_many :favorites
  has_many :favorite_games, through: :favorites, source: 'game'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  add_flash_types :success, :info, :warning, :danger
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  private
    def require_login
      unless logged_in?
        redirect_to login_path, danger: "ログインしてください"
      end
    end  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_login, {only: [:create, :destroy]}
  
  def index
    @favorite_games = current_user.favorite_games
    @user = User.find_by(id: params[:user_id])
  end
  
  def create
    favorite = Favorite.new
    favorite.game_id = params[:game_id]
    favorite.user_id = current_user.id
    if favorite.save
      redirect_to game_path(favorite.game_id), success: "お気に入りに登録しました"
    else
      redirect_to game_path(favorite.game_id), danger: "お気に入り登録に失敗しました"
    end
  end
  
  def destroy
    favorite = Favorite.find_by(game_id: params[:game_id])
    if favorite.destroy
      redirect_to game_path(params[:game_id]), success: "お気に入り解除しました"
    else
      redirect_to game_path(params[:game_id]), danger: "お気に入り解除に失敗しました"
    end
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_login, {only: [:new, :create, :edit, :update]}
  
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(id: @game.id), success: '投稿しました'
    else
      render :new
    end
  end
  
  def index
    @games = Game.all.search(params[:search])
  end
  
  def show
    @game = Game.find_by(id: params[:id])
  end
  
  def edit
    @game = Game.find(params[:id])
  end
  
  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path(@game.id), success: "変更しました"
    else
      render :edit
    end
  end
  
  def rank
    @games_rank = Game.find(Favorite.group(:game_id).order('count(game_id) desc').limit(5).pluck(:game_id))
  end
  
  def search
    if params[:title].present?
      @games = Game.where("title LIKE ?", "%{params[:title]%}")
    else
      @games = Game.none
    end
  end
    
  private
  def game_params
    params.require(:game).permit(:user_id, :image, :title, :description, :genre, :participation, :target_age, :play_time, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @games = Game.all
    @reviews = Review.all
    @games_rank = Game.find(Favorite.group(:game_id).order(Arel.sql('count(game_id) desc')).limit(5).pluck(:game_id))
  end
  
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login, {only: [:new, :edit]}
  
  def new
    @game = Game.find_by(id: params[:game_id])
    @review = Review.new
  end
  
  def create
    @review = Review.new(review_params)
    @game = Game.find_by(params[:id])
    if @review.save
      redirect_to game_path(id: @review.game_id), success: "レビューを投稿しました"
    else
      render :new
    end
  end

  def edit
    @review = Review.find_by(params[:id])
    @game = Game.find_by(id: @review.game_id)
  end
  
  def update
    @review = Review.new(review_params)
    @game = Game.find_by(params[:id])
    if @review.save
      redirect_to game_path(id: @review.game_id), success: "レビューを変更しました"
    else
      render :edit
    end
  end

  def show
    @review = Review.find_by(id: params[:id])
  end
  
  def index
    @reviews = Review.all
  end
  
  private
    def review_params
      params.require(:review).permit(:comment, :evalution, :user_id, :game_id)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: "ログインしました"
    else
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_path, info: "ログアウトしました"
  end
    
  private
    def log_in(user)
      session[:user_id] = user.id
    end
  
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path, success: "登録完了"
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to root_path, notice: "他のアカウントから変更できません"
    elsif @user.update(user_params)
      redirect_to user_path(current_user.id), success: "変更しました"
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation, :description)
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/favorites/_game.html.erb
<% if game != nil %> 
  <div class="top-games inline">
    <%= link_to "#", class: 'link' do %>
      <%= render partial: "pages/game_image", locals: { game: game } %>
      <p class="game-title center"><%= game.title.truncate(10) %></p>
    <% end %>
  </div>
<% end %>

app/views/favorites/index.html.erb
<div class="fovorite-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <div class="favorite-index-container">
          <%= render 'users/introduction' %>
      
          <div class="review-favorite-container">
            <div class="center">
              <p><%= link_to "レビュー一覧", user_path(id: @user.id), class: "items black" %></p>
              <p class="items orange">お気に入り</p>
            </div>
          
            <div class="topics">
              <% @favorite_games.each_slice(4) do |game1, game2, game3, game4| %>
                <%= render partial: "game", locals: { game: game1 } %>
                <%= render partial: "game", locals: { game: game2 } %>
                <%= render partial: "game", locals: { game: game3 } %>
                <%= render partial: "game", locals: { game: game4 } %>
              <% end %>
            </div>
          
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/_games.html.erb
<% if game != nil %>
  <div class="topics inline">
    <%= link_to game_path(id: game.id), class: 'item' do %>
      <% if game.image.present? %>
        <p class='center'><%= image_tag game.image.url, class: 'image' %></p>
      <% else %>
        <p class='center'><%= image_tag "noimage-game.jpg", class: 'image' %></p>
      <% end %>
      <p class="game-title center"><%= game.title.truncate(15) %></p>
      <p class="des"><%= game.description.truncate(100) %></p>
      <div class="center des">
        <%= render partial: "pages/evalution", locals: { game: game } %>
        <%= render partial: "pages/favorite", locals: { game: game } %>
        <p class="count">( <%= game.reviews.count %> 件)</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/games/_rank.html.erb
<div class="left-game-details inline">
  <%= image_tag ranking, class: 'rank-image inline' %>
</div>

app/views/games/_reference.html.erb
<p class="genre">ジャンル　：　<%= game.genre %></p>
<p class="participation">参加人数　：　<%= game.participation %></p>
<p class="target_age">対象年齢　：　<%= game.target_age %></p>
<p class="play_time">プレイ時間　：　<%= game.play_time %></p>
<p class="price">参考価格　：　<%= game.price %></p>
<% if game.reviews.present? %>
  <p class="evaluation">評価　：　<%= game.reviews.average(:evalution) %></p>
<% else %>
  <p class="evaluation">評価　：　ー</p>
<% end %>
<p class="favorite">お気に入り　：　<%= game.favorites.count %></p>

app/views/games/edit.html.erb
<div class="game-edit-wrapper">
  <div class="container">
    <div class="row">
      
       <div class="game-new-container col-md-offset-2 col-md-8">
        <div class="title">
          <p class="game gray">ゲーム内容編集</p>
        </div>
        <div class="entry-field">
         <%= render partial: 'entry-field', locals: { register: "編集" } %>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="game-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="game-index-container col-md-offset-2 col-md-8">
        <div class="title">
          <p class="game gray">ゲーム一覧</p>
        </div>
        <div class="link-btn">
          <%= link_to "ゲーム投稿", new_game_path, class: "btn btn-default" %>
        </div>
        <div class="game-search">
          <%= form_tag(games_path, :method => "get") do %>
            <%= text_field_tag :search, "", {class: "form-control"} %>
            <p class="search-btn"><%= submit_tag "検索" ,:title => nil ,class: "btn btn-default"%></p> 
          <% end %>  
        </div>
        <div class="game-topic">
          <% @games.each_slice(3) do |game1, game2, game3| %>
            <div class="line">
             <%= render partial: "games", locals: { game: game1 } %>
             <%= render partial: "games", locals: { game: game2 } %>
             <%= render partial: "games", locals: { game: game3 } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="game-show-wrapper">
  <div class="container">
    <div class="row">
      <div class="game-show-container col-md-offset-2 col-md-8">
        
        <div class="title-container">
          <p class="title"><%= @game.title %></p>
        </div>
        
        <div class="explanation">
          <div class="left-container inline">
            <%= render partial: "pages/game_image", locals: { game: @game } %>
            <div class="favorite center">
              <% if !@game.favorite_users.include?(current_user) %>
                <%= link_to "お気に入り", favorites_path(game_id: params[:id]), class: "btn btn-default",  method: :post %>
              <% else %>
                <%= link_to "お気に入り解除", favorites_path(game_id: params[:id]), class: "btn btn-warning",  method: :delete %>
              <% end %>
            </div>
            <div class="reference">
              <%= render partial: "reference", locals: { game: @game } %>
            </div>
          </div>
        
          <div class="right-container inline">
            <div class="title-container">
              <p class="item-title gray">ゲーム内容</p>
            </div>
            <p class="description"><%= @game.description %></p>
            <div class="center">
              <%= link_to "説明文編集", edit_game_path(params[:id]), class: "btn btn-default" %>
          </div>
          </div>
        </div>
        
        <div class="review-container">
          <div class="review-title-container">
            <p class="item-title gray">レビュー</p></p>
          </div>
          <div class="link-btn">
            <%= link_to "レビューを書く", new_game_review_path(game_id: @game.id), class: "btn btn-default" %>
          </div>
          
          <div class="post">
            <% if @game.reviews.present? %>
              <% @game.reviews.each do |review| %>
                <div class="review-post">
                  <%= link_to game_review_path(game_id: review.game_id, id: review.id), class: "review-link" do %>
                    <div class="user-image-container inline">
                      <%= render partial: "users/user_image", locals: { user: review.user } %>
                    </div>
                    <div class="comment-container inline">
                    <p class="comment-user-name"><%= review.user.name %>さんのレビュー</p>
                    <p class="comment"><%= review.comment.truncate(160) %></p>
                    <div class="eva-container">
                      <div class="inline eva" id="star-rate-<%= review.id %>"></div>
                        <script>
                          $('#star-rate-<%= review.id %>').raty({
                            size: 36,
                            starOff:  '<%= asset_path('star-off.png') %>',
                            starOn: '<%= asset_path('star-on.png') %>',
                            starHalf: '<%= asset_path('star-half.png') %>',
                            half: true,
                            readOnly: true,
                            score: <%= review.evalution %>,
                          });
                        </script>
                        <p class="inline eva"><%= review.evalution %></p>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <p class="no-review center">投稿を募集しています</p>
            <% end %>
          </div>
        </div>
      
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="jquery.raty.js"></script>
   
  </head>
  
  <body>
    <div class="all-container">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <%= link_to "Games", root_path, class: "navbar-brand" %>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="nav-user">
                <%= link_to current_user.name, user_path(id: current_user.id) %>
              </li>
              <li class="gray">
                <p>|</p>
              </li>
              <li class="new-post">
                <%= link_to "ゲーム一覧", games_path %>
              </li>
              <li class="gray">
                <p>|</p>
              </li>
              <li class="new-post">
                <%= link_to "レビュー一覧", reviews_path %>
              </li>
              <li class="gray">
                <p>|</p>
              </li>
              <li class="new-post">
                <%= link_to "ランキング", rank_games_path %>
              </li>
              <li class="gray">
                <p>|</p>
              </li>
              <li class="nav-logout">
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-signin">
                <%= link_to "新規登録", new_user_path %>
              </li>
              <li class="gray">
                <p>|</p>
              </li>
              <li class="nav-login">
                <%= link_to "ログイン", login_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <div class="main">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
        <% end %>
        <%= yield %>
        <script>
          $(function() {
            $(".alert").fadeOut(5000);
          });
        </script>
      </div>
      <footer>
      <p class="footer-text gray center">Games</p>
      </footer>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-wrapper">
  
  <div class="top-container">
    <div class="images">
      <%= image_tag "game1.jpg",class: "game-image" %>
      <%= image_tag "game2.jpg",class: "game-image" %>
      <%= image_tag "game3.jpg",class: "game-image" %>
    </div>
    <div class="text-container">
      <h1 class="text center">お気に入りのゲームを見つけよう!</h1>
      <div class="buttoms center">
        <a href="#game_show", class="btn btn-default"><%= image_tag "card.png", class: "text-image" %>ゲーム一覧</a>
        <a href="#review_show", class="btn btn-default"><%= image_tag "comment2.png", class: "text-image" %>レビュー一覧</a>
        <a href="#rank_show", class="btn btn-default"><%= image_tag "ranking.png", class: "text-image" %>ランキング</a>
      </div>
    </div>
　</div>
　
　<div class="container">
　  <div class="row">
      <div class="row-container col-md-offset-1 col-md-10">
        <div id="game_show" class="item-container">
          <%= link_to "ゲーム一覧", games_path, class: "item-name" %>
          <div class="topic center">
            <% @games.first(5).each do |game| %>
              <div class="top-games">
                <%= link_to game_path(id: game.id), class: 'item' do %>
                  <%= render partial: "game_image", locals: { game: game } %>
                  <p class="game-title center"><%= game.title.truncate(10) %></p>
                  <div class="center">
                    <%= render partial: "evalution", locals: { game: game } %>
                    <p class="count">( <%= game.reviews.count %> 件)</p>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div id="review_show" class="item-container">
          <%= link_to "レビュー一覧", reviews_path, class: "item-name" %>
          <div class="review-topic center">
            <% @reviews.first(5).each do |review| %>
              <div class="top-games">
                <%= link_to game_review_path(game_id: review.game_id, id: review.id), class: 'item' do %>
                  <%= render partial: "game_image", locals: { game: review.game } %>
                  <p class="game-title center"><%= review.game.title.truncate(10) %></p>
                  <p class="des"><%= review.comment.truncate(55) %></p>
                  <p class="user-name center">by <%= review.user.name %>  </p>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div id="rank_show" class="item-container">
          <%= link_to "ランキング", rank_games_path, class: "item-name" %>
          <div class="topic center">
            <div class="top-games">
              <% if @games_rank.first.present? %>
                <%= link_to game_path(id: @games_rank.first.id), class: 'item' do %>
                  <div class="game-image">
                    <div class="rank-background center">
                      <p class="rank">1</p>
                    </div>
                    <%= render partial: "game_image", locals: { game: @games_rank.first } %>
                  </div>
                  <%= render partial: "rank_game", locals: { game: @games_rank.first } %>
                <% end %>
              <% end %>
            </div>
            <div class="top-games">
              <% if @games_rank.second.present? %>
                <%= link_to game_path(id: @games_rank.second.id), class: 'item' do %>
                  <div class="game-image">
                    <div class="rank-background center">
                      <p class="rank">2</p>
                    </div>
                    <%= render partial: "game_image", locals: { game: @games_rank.second } %>
                  </div>
                  <%= render partial: "rank_game", locals: { game: @games_rank.second } %>
                <% end %>
              <% end %>
            </div>
            <div class="top-games">
              <% if @games_rank.third.present? %>
                <%= link_to game_path(id: @games_rank.third.id), class: 'item' do %>
                  <div class="game-image">
                    <div class="rank-background center">
                      <p class="rank">3</p>
                    </div>
                    <%= render partial: "game_image", locals: { game: @games_rank.third } %>
                  </div>
                  <%= render partial: "rank_game", locals: { game: @games_rank.third } %>
                <% end %>
              <% end %>
            </div>
            <div class="top-games">
              <% if @games_rank.fourth.present? %>
                <%= link_to game_path(id: @games_rank.fourth.id), class: 'item' do %>
                  <div class="game-image">
                    <div class="rank-background center">
                      <p class="rank">4</p>
                    </div>
                    <%= render partial: "game_image", locals: { game: @games_rank.fourth } %>
                  </div>
                  <%= render partial: "rank_game", locals: { game: @games_rank.fourth } %>
                <% end %>
              <% end %>
            </div>
            <div class="top-games">
              <% if @games_rank.fifth.present? %>
                <%= link_to game_path(id: @games_rank.fifth.id), class: 'item' do %>
                  <div class="game-image">
                    <div class="rank-background center">
                      <p class="rank">5</p>
                    </div>
                    <%= render partial: "game_image", locals: { game: @games_rank.fifth } %>
                  </div>
                  <%= render partial: "rank_game", locals: { game: @games_rank.fifth } %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <script>
    $(function() {
      $('.images').not('.slick-initialized').slick({
        autoplay: true,
        autoplaySpeed: 3000,
        });
     });
  </script>
  
  <script>
    $('a[href^="#"]').click(function() {
      var headerHight = 80;
      var speed = 400; 
      var href = $(this).attr("href");
      var target = $(href == "#" || href == "" ? 'html' : href);
      var position = target.offset().top - headerHight;
      $('body,html').animate({scrollTop: position}, speed, 'swing');
      return false;
    });
  </script>
  
</div>
    

app/views/reviews/_reviews.html.erb
<% if review != nil %>
  <div class="review inline">
    <%= link_to game_review_path(game_id: review.game_id, id: review.id), class: "item" do %>
      <%= render partial: "pages/game_image", locals: { game: review.game } %>
      <p class="game-title center"><%= review.game.title.truncate(10) %></p>
      <p class="des"><%= review.comment.truncate(55) %></p>
      <p class="user-name center">by <%= review.user.name %>  </p>
    <% end %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<div class="review-show-wrapper">
  <div class="container">
    <div class="row">
      <div class="review-show-container col-md-offset-2 col-md-8">
        
        <div class="title-container">
          <p class="title"><%= @review.game.title %></p>
        </div>
        
        <div class="review-container">
          <div class="left-review inline">
            <%= link_to user_path(id: @review.user_id) do %>
              <%= image_tag @review.user.image.url, class: 'user-image' %>
            <% end %>
          </div>
          <div class="right-review inline">
            <div class="title-container">
              <p class="title"><%= @review.user.name %>のレビュー</p>
            </div>
            <p class="review"><%= @review.comment %></p>
            <% if current_user.id == @review.user.id %>
              <div class="center">
                <%= link_to "レビューを編集", edit_game_review_path(game_id: @review.game_id, id: @review.id), class: "btn btn-default" %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="game-detail center">
          <%= link_to game_path(id: @review.game.id), class: "game-reference" do %>
            <div class="left-game-detail inline">
              <%= render partial: "pages/game_image", locals: { game: @review.game } %>
            </div>
            <div class="right-game-detail inline">
              <%= render partial: "games/reference", locals: { game: @review.game } %>
            </div>
          <% end %>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/users/_introduction.html.erb
<div class="introduction-container">
  <div class="image inline">
    <% if @user.image.present? %>
      <%= image_tag @user.image.url, class: "user-image center" %>
    <% else %>
      <%= image_tag "noimage-man.jpg", class: "user-image center" %>
    <% end %>
  </div>
  <div class="user-introduction inline">
    <h3 class="user-name"><%= @user.name %></h3>
    <% if @user.description.present? %>
      <p class="self-introduction gray"><%= @user.description %></p> 
    <% end %>
    <% if current_user.id == @user.id %>
      <p><%= link_to "設定", edit_user_path(id: current_user.id), class: "gray btn btn-default" %></p>
    <% end %>
  </div>
</div>

app/views/users/_review.html.erb
<% if review != nil %>
  <div class="top-games inline">
    <%= link_to game_review_path(game_id: review.game_id, id: review.id), class: 'link' do %>
      <%= render partial: "pages/game_image", locals: { game: review.game } %>
      <p class="game-title center"><%= review.game.title.truncate(10) %></p>
      <p class="des"><%= review.comment.truncate(55) %></p>
      <p class="user-name center">by <%= review.user.name %>  </p>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="user-show-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <div class="user-show-container">
          <%= render 'introduction' %>
        
          <div class="review-favorite-container">
            <div class="center">
              <p class="items orange">レビュー一覧</p>
              <p><%= link_to "お気に入り", user_favorites_path(user_id: params[:id]), class: "items black" %></p>
            </div>
          
            <div class="topics">
              <% @user.reviews.each_slice(4) do |review1, review2, review3, review4| %>
                <%= render partial: "review", locals: { review: review1 } %>
                <%= render partial: "review", locals: { review: review2 } %>
                <%= render partial: "review", locals: { review: review3 } %>
                <%= render partial: "review", locals: { review: review4 } %>
              <% end %>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>